/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE6 (number 53), HD_ROW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW1_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTE2 (number 54), HD_ROW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW2_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA13 (number 55), HD_ROW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW3_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW3_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW3_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW3_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE0 (number 60), HD_ROW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW4_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW4_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW4_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW4_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA10 (number 58), HD_ROW5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW5_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW5_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW5_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW5_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE1 (number 59), HD_ROW6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW6_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW6_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW6_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW6_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC16 (number 28), HD_COL1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_COL1_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL1_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_COL1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_COL1_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_COL1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_COL1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC17 (number 27), HD_COL2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_COL2_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_COL2_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_COL2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_COL2_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_COL2_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB4 (number 19), HD_COL3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_COL3_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL3_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_COL3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_COL3_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_COL3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_COL3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC3 (number 20), HD_COL4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_COL4_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL4_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL4_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_COL4_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_COL4_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_COL4_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_COL4_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC2 (number 21), HD_COL5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_COL5_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL5_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_COL5_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_COL5_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_COL5_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_COL5_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_COL5_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
