/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MKE17Z256xxx7
package_id: MKE17Z256VLH7
mcu_data: ksdk2_0
processor_version: 24.12.10
pin_labels:
- {pin_num: '53', pin_signal: TSI0_CH0/PTE6/LPSPI0_PCS2/LPUART1_RTS, label: HD_ROW1, identifier: HD_ROW1}
- {pin_num: '54', pin_signal: TSI0_CH1/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS, label: HD_ROW2, identifier: HD_ROW2}
- {pin_num: '55', pin_signal: TSI0_CH2/PTA13/LPUART0_RX, label: HD_ROW3, identifier: HD_ROW3}
- {pin_num: '60', pin_signal: TSI0_CH7/PTE0/LPSPI0_SCK/TCLK1, label: HD_ROW4, identifier: HD_ROW3;HD_ROW4}
- {pin_num: '58', pin_signal: TSI0_CH5/PTA10/LPUART0_TX/FXIO_D0, label: HD_ROW5, identifier: HD_ROW5}
- {pin_num: '59', pin_signal: TSI0_CH6/PTE1/LPSPI0_SIN/LPI2C0_HREQ, label: HD_ROW6, identifier: HD_ROW6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '53', peripheral: GPIOE, signal: 'GPIO, 6', pin_signal: TSI0_CH0/PTE6/LPSPI0_PCS2/LPUART1_RTS, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '54', peripheral: GPIOE, signal: 'GPIO, 2', pin_signal: TSI0_CH1/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '55', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: TSI0_CH2/PTA13/LPUART0_RX, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '60', peripheral: GPIOE, signal: 'GPIO, 0', pin_signal: TSI0_CH7/PTE0/LPSPI0_SCK/TCLK1, identifier: HD_ROW4, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '58', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: TSI0_CH5/PTA10/LPUART0_TX/FXIO_D0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '59', peripheral: GPIOE, signal: 'GPIO, 1', pin_signal: TSI0_CH6/PTE1/LPSPI0_SIN/LPI2C0_HREQ, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t HD_ROW5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW5_GPIO, BOARD_INITPINS_HD_ROW5_PIN, &HD_ROW5_config);

    gpio_pin_config_t HD_ROW3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW3_GPIO, BOARD_INITPINS_HD_ROW3_PIN, &HD_ROW3_config);

    gpio_pin_config_t HD_ROW4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE0 (pin 60)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW4_GPIO, BOARD_INITPINS_HD_ROW4_PIN, &HD_ROW4_config);

    gpio_pin_config_t HD_ROW6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE1 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW6_GPIO, BOARD_INITPINS_HD_ROW6_PIN, &HD_ROW6_config);

    gpio_pin_config_t HD_ROW2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE2 (pin 54)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW2_GPIO, BOARD_INITPINS_HD_ROW2_PIN, &HD_ROW2_config);

    gpio_pin_config_t HD_ROW1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE6 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_HD_ROW1_GPIO, BOARD_INITPINS_HD_ROW1_PIN, &HD_ROW1_config);

    /* PORTA10 (pin 58) is configured as PTA10 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW5_PORT, BOARD_INITPINS_HD_ROW5_PIN, kPORT_MuxAsGpio);

    /* PORTA13 (pin 55) is configured as PTA13 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW3_PORT, BOARD_INITPINS_HD_ROW3_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin 60) is configured as PTE0 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW4_PORT, BOARD_INITPINS_HD_ROW4_PIN, kPORT_MuxAsGpio);

    /* PORTE1 (pin 59) is configured as PTE1 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW6_PORT, BOARD_INITPINS_HD_ROW6_PIN, kPORT_MuxAsGpio);

    /* PORTE2 (pin 54) is configured as PTE2 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW2_PORT, BOARD_INITPINS_HD_ROW2_PIN, kPORT_MuxAsGpio);

    /* PORTE6 (pin 53) is configured as PTE6 */
    PORT_SetPinMux(BOARD_INITPINS_HD_ROW1_PORT, BOARD_INITPINS_HD_ROW1_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
