/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE6 (number 53), HD_ROW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW1_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTE2 (number 54), HD_ROW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW2_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA13 (number 55), HD_ROW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW3_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW3_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW3_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW3_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW3_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE0 (number 60), HD_ROW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW4_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW4_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW4_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW4_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW4_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA10 (number 58), HD_ROW5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW5_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW5_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW5_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW5_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW5_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE1 (number 59), HD_ROW6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HD_ROW6_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HD_ROW6_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HD_ROW6_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HD_ROW6_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HD_ROW6_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
